### ISSUE TITLE
this package doesn't compile

### ISSUE THREAD

**Issue by fvigotti** [spring-cloud-stream-app-starters/trigger#1]
Hi,
I'm having problems using this trigger as dependency in other project
also this same project doesn't seems to build to me.. at least using
those build instruction 
https://github.com/spring-cloud-stream-app-starters/trigger/blob/master/spring-cloud-starter-stream-source-trigger/README.adoc

( tested on both master && 1.3.x branch ) 
`$ ./mvnw clean install -PgenerateApps`
give this output
```
[INFO] Compiling 1 source file to /tmp/trigger/spring-cloud-starter-stream-source-trigger/target/test-classes
[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
[ERROR] /tmp/trigger/spring-cloud-starter-stream-source-trigger/src/test/java/org/springframework/cloud/stream/app/trigger/source/TriggerSourceTests.java:[29,52] package org.springframework.cloud.stream.test.binder does not exist
[ERROR] /tmp/trigger/spring-cloud-starter-stream-source-trigger/src/test/java/org/springframework/cloud/stream/app/trigger/source/TriggerSourceTests.java:[48,19] cannot find symbol
  symbol:   class MessageCollector
  location: class org.springframework.cloud.stream.app.trigger.source.TriggerSourceTests
```

**Comment by fvigotti** [comment]
maybe this is missing ? 
```
<dependency>
			<groupId>org.springframework.cloud</groupId>
			<artifactId>spring-cloud-stream-test-support</artifactId>
			<scope>test</scope>
		</dependency>
```

**Comment by olegz** [comment]
@fvigotti Indeed. We're still in the process of upgrading our starters to account for changes and improvements before 2.0 release of spring cloud stream. One of these changes is new test binder (blog and details are coming shortly), hence the issue you see.
In any event, adding the above dependency should take care of the issue.
